version: '3.7'

services:
  api-service:
    restart: always
    ports:
      - 8081:8081
    image: grpc_server_message:latest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge